### ISSUE TITLE
Verify Chart

### ISSUE THREAD

**Issue by mumusa** [Silence-GitHub/BBMetalImage#1]
How to verify test chart

**Comment by Silence-GitHub** [comment]
Do you mean the performance test including GPUImage?

**Comment by mumusa** [comment]
@Silence-GitHub 是的(・o・)

**Comment by Silence-GitHub** [comment]
正如README里写的，测试代码在CompareImageLib工程里，要真机运行。目前测试了iPhone7，iOS 12.1。测试结果在CompareImageLib.numbers里。
