### ISSUE TITLE
How to fix aliasing problem in BBMetalView?

### ISSUE THREAD

**Issue by hoangdado** [Silence-GitHub/BBMetalImage#10]
Hi @Silence-GitHub, I just tested your demo with and without filter camera preview but the output looked aliasing. You can concentrate on the edge region to see the different with with the default camera. Hopefully you can fix it soon. Thanks!

**Comment by Silence-GitHub** [comment]
Version 1.0.5 fixes it.

**Comment by hoangdado** [comment]
Thanks @Silence-GitHub, it seem to work
