### ISSUE TITLE
How to track recording duration?

### ISSUE THREAD

**Issue by hoangdado** [Silence-GitHub/BBMetalImage#11]
Hi @Silence-GitHub, could you please add a way to track video recording duration to BBMetalVideoWriter?

**Comment by Silence-GitHub** [comment]
Do you mean calculating the whole duration of writing a video? If so, keep the start time and the end time to calculate.

Or do you mean calculating the duration of writing one frame? How about adding a progress callback after writing a frame? So you can do whatever you want after writing each frame.

**Comment by hoangdado** [comment]
Thanks @Silence-GitHub, What I want is a progress callback.

**Comment by Silence-GitHub** [comment]
Version 1.0.7 adds video writer progress callback.

```
videoWriter.start { (type) in
    switch type {
        case let .video(time, success): print("Video time = \(time), success = \(success)")
        case let .audio(time, success): print("Audio time = \(time), success = \(success)")
    }
}
```

**Comment by hoangdado** [comment]
Hi @Silence-GitHub, thanks for your quick response, but what I mean is the elapsed time (may be CMTime or CGFloat seconds value) from videoWriter.start()

**Comment by Silence-GitHub** [comment]
I think providing the video time in progress callback is more reasonable. You can track the elapsed time like this.

```
let startTime = CACurrentMediaTime()
videoWriter.start { (type) in
    let duration = CACurrentMediaTime() - startTime
}
```

**Comment by hoangdado** [comment]
@Silence-GitHub, thank you so much!
