### ISSUE TITLE
How to replay BBMetalVideoSource when finished?

### ISSUE THREAD

**Issue by hoangdado** [Silence-GitHub/BBMetalImage#12]
Hi @Silence-GitHub, sorry for bother you again, I want to preview a video filter using your "Process Video File" example. Here is what I tried: 
`
        videoSource.add(consumer: contrastFilter)
                .add(consumer: lookupFilter)
                .add(consumer: sharpenFilter)
                .add(consumer: metalView)
`
It worked fine but you can only preview one time. So could you please add an option to replay the BBMetalVideoSource when it finished? Further more, I think you should add the playback feature to BBMetalVideoSource to support developers who want to use your library to create a video editor application. 
Thank you so much!

**Comment by pennywise94** [comment]
Any solution for this? Facing the same issue.
