### ISSUE TITLE
VideoFilterVC rotates some videos

### ISSUE THREAD

**Issue by sebastianroth1** [Silence-GitHub/BBMetalImage#17]
Videos  which were recorded with an iPhones (tested with: iPhone 6, iOS 12.1 and iPhone 11, iOS 13) and put in the VideoFilterVC.swift controller in the demo project are rotated by -90°.

I loaded a video recorded with the iPhone into the project bundle and replaced the default video "test_video.mov". When I run the App, the video is rotated. However, the default "test_video.mov" file is output correctly. So some videos are rotated, others are displayed correctly.

This bug can be worked around with applying a `BBMetalRotateFilter(angle: 90, fitSize: true)`, but is not a good fix because it only adresses some videos. 

Does anyone have a solution to this?

**Comment by lygialiem** [comment]
Hi heythiswildidea!

I'm facing this issue, too. Have you had the solution for that?

**Comment by Silence-GitHub** [comment]
One solution is getting the video orientation first (e.g. `preferredTransform ` of `AVAsset`). Add `BBMetalRotateFilter` and/or `BBMetalFlipFilter` to change the orientation.

**Comment by Prempriya08** [comment]
I am also facing the same issue after picking videos from phone library. Please help.

**Comment by Silence-GitHub** [comment]
Version 1.1.7 fixes it. Please try version 1.1.7
