### ISSUE TITLE
Convert metalView to Data

### ISSUE THREAD

**Issue by pennywise94** [Silence-GitHub/BBMetalImage#20]
Hi,
I was wondering if there is a way to convert the playing video, with filters and effects applied, to a Data object. Or should I first save the video locally and then get the contents of the file? This would take a bit longer to process as I need to wait for the saving first and it seems a bit unnecessary in my opinion.

Thanks!

**Comment by Silence-GitHub** [comment]
You should save the video and then get the contents of file. I don't think there is a way to get a data object.

**Comment by pennywise94** [comment]
Got it working by, indeed, first saving the video locally. Then I obtain the data of this local file, and I remove all locally saved videos periodically so it doesn't take up too much space on someone's device.
