### ISSUE TITLE
Black pixels on the Image when using .hueFilter

### ISSUE THREAD

**Issue by heythiswildidea** [Silence-GitHub/BBMetalImage#22]
When I use the static image hueFilter, black pixels will appear on the filtered image. 
This happens on iPhone 5s - iPhone 10, but not on iPhone 11.
I tested the hue filter in the demo project with [this photo](https://www.pexels.com/de-de/foto/iphone-8-plus-896172/) and did not make any changes in the code.
On the filtered image you can see the black pixels:
![image](https://user-images.githubusercontent.com/55516769/67475243-1e733d80-f656-11e9-81ac-5bc3e5d7c642.png)
The black pixels also occur sometimes with other filters.

**Comment by Silence-GitHub** [comment]
@heythiswildidea Thank you for issuing me. For hue filter, replacing `half4` with `float4` in the shader solves the problem. Could you please tell me which filters have the same problem? I will fix them in the new version.

**Comment by heythiswildidea** [comment]
Good job! Thank you for solving this problem! 
I just did some more tests. Apparently only this filter is affected.

**Comment by Silence-GitHub** [comment]
Version 1.0.10 fixes it.
