### ISSUE TITLE
Project Support Issues

### ISSUE THREAD

**Issue by iDevid** [Silence-GitHub/BBMetalImage#23]
With the latest update you removed BBMetalMatrix4x4 object, breaking the code on production project.
I suggest for the next version to deprecate gradually these things instead of removing them.

Another issue is that there isn't a CHANGELOG for this project, so I have to see commits to see what changes were made...

**Comment by iDevid** [comment]
Another thing, you used float4 in your code, but it's deprecated by simd

**Comment by Silence-GitHub** [comment]
@iDevid Good issues! Thank you! I will work on these.

**Comment by Silence-GitHub** [comment]
@iDevid Hi, I have replaced float4 with SIMD4<Float>, and added a CHANGELOG.

**Comment by iDevid** [comment]
Great! :D
