### ISSUE TITLE
How to access AVCaptureDevice

### ISSUE THREAD

**Issue by pennywise94** [Silence-GitHub/BBMetalImage#27]
I am currently wondering if it is possible to access the AVCaptureDevice of the BBMetalCamera. I am trying to implement some logic towards enabling/disabling flash, zooming in/out on the camera, ...

Any ideas?

**Comment by Silence-GitHub** [comment]
Use `configureCamera(_ block: (AVCaptureDevice) -> Void)` method

```
camera.configureCamera { device in
    if device. isFlashAvailable {
        // Enable flash
    }
}
```

**Comment by pennywise94** [comment]
Awesome.
