### ISSUE TITLE
App crash on BBMetalDevice MTLCreateSystemDefaultDevice()

### ISSUE THREAD

**Issue by LeanneSc** [Silence-GitHub/BBMetalImage#3]
I have added your framework to my test application and when trying to activate a filter, the app crashes on MTLCreateSystemDefaultDevice() while running on a simulator

"Fatal error: Unexpectedly found nil while unwrapping an Optional value"

I have even tried running the demo app  in the simulator with the same crash. 
This seems to only happen in the simulator

Can you possibly assist?

**Comment by Silence-GitHub** [comment]
Metal is not supported in the iOS Simulator.
See https://forums.developer.apple.com/thread/31120

**Comment by LeanneSc** [comment]
Thank you for the feedback
