### ISSUE TITLE
video not show after remove consumer and add some new consumers 

### ISSUE THREAD

**Issue by R3l0ad3d** [Silence-GitHub/BBMetalImage#34]
when i remove all consumer and add new consumers then metal view not show video . its the main problem . any one help ?
videoSource?.removeAllConsumers()
                videoSource?.add(consumer: box)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                videoSource?.add(consumer: videoWriter!)
this is my code . even if i add new consumer after first time thats not effect on view . here i want to change "box" consumer to any other filter consumer . rest of consumer are same . how can i do that . if i remove first and add to consumer first index then view not show that effect .

**Comment by R3l0ad3d** [comment]
when i remove all consumer and add new consumer then metal view not show video . its the main problem . any one help ?

**Comment by R3l0ad3d** [comment]
Any one help please . I am stack for that .

**Comment by Silence-GitHub** [comment]
All sources should remove consumers.

```
videoSource?.removeAllConsumers()
box.removeAllConsumers()
lutFilter!.removeAllConsumers()

videoSource?.add(consumer: otherFilter)
    .add(consumer: lutFilter!)
    .add(consumer: metalView!)
```

**Comment by R3l0ad3d** [comment]
`var commonFilter : BBMetalBaseFilter?
case .Normal:
                let gaussian = BBMetalGaussianBlurFilter(sigma: 10)
                
                videoSource?.removeAllConsumers()
                lutFilter?.removeAllConsumers()
                commonFilter?.removeAllConsumers()
                
                //current filter
                commonFilter = gaussian
                
                videoSource?.add(consumer: gaussian)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                
            
                break
            case .Box:
                let box = BBMetalBoxBlurFilter(kernelWidth: 5, kernelHeight: 5)
                
                videoSource?.removeAllConsumers()
                commonFilter?.removeAllConsumers()
                lutFilter?.removeAllConsumers()
                
                //current filter
                commonFilter = box
                
                videoSource?.add(consumer: box)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                videoSource?.add(consumer: videoWriter!)
                
            break`
that is my code but its still no update metal view when i change initial consumer to this consumers . please help

**Comment by Silence-GitHub** [comment]
1. Could you please show more code?
2. See the demo project. You may find what you need

**Comment by R3l0ad3d** [comment]
ok i gave you my class . i think you can understand . i have a collection view which hold the blur option . if i click Gaussian blur view effect change to Gaussian , if i click box blur video effect change to box blur . and i have more filter like blur . video play background but metal view stack after change filter . 
`class BBMetalBackgroundVideoView: UIView {

    var backgroundImageView : UIImageView?
    var metalView : BBMetalView?
    var videoSource : BBMetalVideoSource?
    var videoWriter : BBMetalVideoWriter?
    
    var sourceUrl : URL?
    var outputUrl : URL?
    
    var lutFilter : BBMetalLookupFilter?
    var commonFilter : BBMetalBaseFilter?
    
    //reset variables
    var isVideoBackground : Bool = true
    var isBackgroundColor : Bool = false
    
    var ivBackgroundColor : UIColor?
    
    var backgroundImage : UIImage?
    var tempBackgroundImage : UIImage?
    
    var blurClass : (blur: BlurClass,intensity: Float)?
    var tempBlurClass : (blur: BlurClass,intensity: Float)?
    
    var lutImage : UIImage?
    var tempLutImage : UIImage?
    var filterIntensity : Float?
    var tempFilterIntensity : Float?
    
    var firstFrameImage : UIImage?
    var isPotrait : Bool = true
    
    
    /*
    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        // Drawing code
    }
    */
    
    override func awakeFromNib() {
        super.awakeFromNib()
        commonInit()
    }
    override init(frame: CGRect) {
        super.init(frame: frame)
        commonInit()
    }
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

    private func commonInit()  {
        metalView = BBMetalView(frame: self.bounds)
        metalView?.backgroundColor = .yellow
        metalView?.translatesAutoresizingMaskIntoConstraints = false
       self.addSubview(metalView!)
       metalView?.snp.makeConstraints({ (make) in
           make.top.equalToSuperview()
           make.bottom.equalToSuperview()
           make.left.equalToSuperview()
           make.right.equalToSuperview()
       })
        metalView?.bb_textureContentMode = .aspectRatioFill
        metalView?.enableSetNeedsDisplay = true
        backgroundImageView = UIImageView()
        backgroundImageView?.contentMode = .scaleAspectFill
        backgroundImageView?.translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(backgroundImageView!)
        backgroundImageView?.snp.makeConstraints({ (make) in
            make.top.equalToSuperview()
            make.bottom.equalToSuperview()
            make.left.equalToSuperview()
            make.right.equalToSuperview()
        })
        backgroundImageView?.isHidden = true
        
        layoutIfNeeded()
    }
    
    func initialPlaySetup(url : URL, isPotrait : Bool)  {
        //update all flag
        self.isVideoBackground = true
        self.isBackgroundColor = false
        self.tempBackgroundImage = nil
        self.backgroundImage = nil
        self.lutImage = nil
        self.tempLutImage = nil
        self.blurClass = nil
        self.tempBlurClass = nil
        self.ivBackgroundColor = nil
        self.isPotrait = isPotrait
        
        self.sourceUrl = url
        metalView?.reloadInputViews()
        if outputUrl != nil{
            do{
                try FileManager.default.removeItem(at: outputUrl!)
            }catch{
                print(error)
            }
        }
        let milliseconds : Int = Int(NSDate.init().timeIntervalSince1970 * 1000)
        outputUrl = FileManager.default.temporaryDirectory
        outputUrl?.appendPathComponent("\(milliseconds)")
        outputUrl?.appendPathExtension(sourceUrl!.pathExtension)
        
        do{
            try FileManager.default.removeItem(at: outputUrl!)
        }catch{
            print(error)
        }
        
        
        let asset = AVAsset(url: url)
        firstFrameImage = asset.getFirstFrameImage()
        let outputSize = asset.getActualViewSize()
        

        backgroundImageView?.isHidden = false
        let bImg = firstFrameImage!.gaussianBlurBB(blurRadius: 10)
        backgroundImageView?.image = bImg.rotate(radians: .pi/2)
        
        
        self.videoSource = BBMetalVideoSource(url: url)
        
        self.videoWriter = BBMetalVideoWriter(url: outputUrl!, frameSize: BBMetalIntSize(width: Int(outputSize.width), height: Int(outputSize.height)))
        
        self.videoSource!.playWithVideoRate = true
        
        commonFilter = BBMetalGaussianBlurFilter(sigma: 10)
        
        
        
        let lut = UIImage(named: "lookup.png")
        self.lutImage = lut
        lutFilter = BBMetalLookupFilter(lookupTable: (lut?.bb_metalTexture)!)
        
        
        
        self.videoSource?
            .add(consumer: commonFilter!)
            .add(consumer: lutFilter!)
            .add(consumer: metalView!)
        
        //self.videoSource?.add(consumer: videoWriter!)

        self.videoSource?.start()
        
//        self.videoSource?.start(progress: { time in
//
//        }, completion: { (isComplete) in
//
//        })
    }
    
    func setBlur(blurClass : BlurClass,intensity : Float) {
        
        //self.videoSource = BBMetalVideoSource(url: sourceUrl!)
        //self.videoSource!.playWithVideoRate = true
        
        if blurClass.isPermium{
            self.tempBlurClass = self.blurClass
        }else {
            self.tempBlurClass = nil
        }
   
        if isVideoBackground{
            videoSource?.cancel()
            blurOnVideo(blurClass: blurClass, intensity: intensity)
        }else {
            if blurClass.isBlur{
                let img = blurApply(img: backgroundImage, blur: blurClass.blurName!, value: intensity)
                self.backgroundImageView?.image = img
            }else {
                let img = backgroundImage?.multipleBlendWithBlurBB(blendImage: UIImage(named: blurClass.blendImage!)!)
                self.backgroundImageView?.image = img
            }
            
        }
        
 
    }
    
    private func blurOnVideo(blurClass : BlurClass,intensity : Float){
//        self.videoSource = nil
//        self.videoSource = BBMetalVideoSource(url: sourceUrl!)
//        self.videoSource?.playWithVideoRate = true
//        //videoSource?.resetBenchmark()
//        self.metalView?.removeFromSuperview()
//        metalView = BBMetalView(frame: self.bounds)
//        self.addSubview(metalView!)
        
        if blurClass.isBlur{
                    
            let blur = blurClass.blurName
            
            switch blur {
            case .NoBlur:
                
                backgroundImageView?.isHidden = false
                

                if isPotrait{
                    backgroundImageView?.image = firstFrameImage!
                }else {
                    backgroundImageView?.image = firstFrameImage!.rotate(radians: .pi/2)
                }
                lutFilter?.removeAllConsumers()
                commonFilter?.removeAllConsumers()
                
                videoSource?
                    .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                    
                break
            case .Normal:
                
                videoSource?.removeAllConsumers()
                lutFilter?.removeAllConsumers()
                commonFilter?.removeAllConsumers()
                
                commonFilter = BBMetalGaussianBlurFilter(sigma: 10)
                
                let img = commonFilter!.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
           
                videoSource?.add(consumer: commonFilter!)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                
            
                break
            case .Box:
                videoSource?.removeAllConsumers()
                commonFilter?.removeAllConsumers()
                lutFilter?.removeAllConsumers()
                
                commonFilter = BBMetalBoxBlurFilter(kernelWidth: 5, kernelHeight: 5)
            
                let img = commonFilter!.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
            
                videoSource?.add(consumer: commonFilter!)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                videoSource?.add(consumer: videoWriter!)
                
            break
            case .Bilateral:
                
                let bilateral = BBMetalBilateralBlurFilter()
                
                let img = bilateral.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: bilateral)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                break
            case .Motion:
                let motion = BBMetalBilateralBlurFilter()
                motion.distanceNormalizationFactor = 10
                
                let img = motion.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: motion)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                    
                break
            case .Zoom:
                let zoom = BBMetalZoomBlurFilter()
                zoom.blurSize = 10
                
                let img = zoom.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: zoom)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                    
                break
            case .Pixellet:
                let pixellet = BBMetalPixellateFilter()
                
                let img = pixellet.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: pixellet)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                    
                break
            case .PPixellet:
                let polarPixel = BBMetalPolarPixellateFilter()
                
                let img = polarPixel.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: polarPixel)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                
                break
            case .Dot:
                let dot = BBMetalPolkaDotFilter()
                
                let img = dot.filteredImage(with: firstFrameImage!)
                if isPotrait{
                    backgroundImageView?.image = img
                }else {
                    backgroundImageView?.image = img!.rotate(radians: .pi/2)
                }
                backgroundImageView?.isHidden = false
                
                videoSource?.removeAllConsumers()
                videoSource?.add(consumer: dot)
                .add(consumer: lutFilter!)
                    .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
                
            break
            
            default:
                videoSource!.add(consumer: lutFilter!)
                .add(consumer: metalView!)
                //videoSource?.add(consumer: videoWriter!)
            }
        }else {
            //blend code
        }
    }
    private func blurApply(img : UIImage!, blur : BlurName, value : Float) -> UIImage{
        
        switch blur {
        case .NoBlur:
            return img!
        case .Normal:
            return img!.gaussianBlurBB(blurRadius: value)
        case .Box:
            return img!.boxBlurBB(blurRadius: value)
        case .Bilateral:
            return img!.bilateralBlurBB(distanceNormalizationFactor: value)
        case .Motion:
            return img!.motionBlurBB(blurSize: value)
        case .Zoom:
            return img!.zoomBlurBB(blurSize: value)
        case .Pixellet:
            return img!.pixelletBB(fractionalWidth: value)
        case .PPixellet:
            return img!.polarPixelletBB(pixelSize: value)
        case .Dot:
            return img!.polkaDotBB(dotScaling: value)
        
        }
        
    }
    func setFilter(lut : UIImage,intensity : Float, isPremium : Bool)  {
        if isPremium{
            tempLutImage = lutImage
            tempFilterIntensity = filterIntensity
        }else {
            tempLutImage = nil
        }
        lutImage = lut
        filterIntensity = intensity
        
        if isVideoBackground{
            lutFilter!.lookupTable = lut.bb_metalTexture!
            lutFilter!.intensity = intensity
        }else {
            if ivBackgroundColor == nil{
                let image = backgroundImageView?.image
                if image != nil{
                    let filterImage = image?.filterFromLutBB(lut: lut, intensity: intensity)
                    self.backgroundImageView?.image = filterImage
                }
            }
            
        }
    }
    
    func setBackgroundImage(backImage : UIImage, isPremium : Bool)  {
        videoSource?.cancel()
        
        if isPremium{
            self.tempBackgroundImage = self.backgroundImage
       
        }else {
            self.tempBackgroundImage = nil
            self.isVideoBackground = false
        }
        self.isBackgroundColor = false
        self.ivBackgroundColor = nil
        
        
        self.backgroundImage = backImage
        
        self.backgroundImageView?.isHidden = false
        self.backgroundImageView?.image = backImage
        
    }
    
    func setIvBackgroundColor(color : UIColor)  {
        self.ivBackgroundColor = color
        //update flag
        self.isBackgroundColor = true
        self.isVideoBackground = false
        self.tempBackgroundImage = nil
        self.backgroundImage = nil
        
        //update image view
        self.backgroundImageView?.isHidden = false
        self.backgroundImageView?.image = nil
        
        
        self.backgroundImageView?.backgroundColor = color
    }
    
    func previousStage()  {
        if isVideoBackground{
            self.backgroundImageView?.isHidden = true
            // blur change
            if tempBlurClass != nil && blurClass != nil {
                self.blurClass = tempBlurClass
                blurOnVideo(blurClass: self.blurClass!.blur, intensity: self.blurClass!.intensity)
            }
            if tempLutImage != nil && lutImage != nil{
                self.lutImage = self.tempLutImage
                setFilter(lut: self.lutImage!, intensity: self.filterIntensity!, isPremium: false)
            }
            
        }else {
            if ivBackgroundColor == nil{
                self.backgroundImage = self.tempBackgroundImage
                
                if tempBlurClass != nil && blurClass != nil {
                    self.blurClass = tempBlurClass
                    let img = blurApply(img: self.backgroundImage, blur: self.blurClass!.blur.blurName!, value: self.blurClass!.intensity)
                    self.backgroundImageView?.image = img
                }
                if tempLutImage != nil && lutImage != nil{
                    lutImage = tempLutImage
                    self.lutImage = self.tempLutImage
                    setFilter(lut: self.lutImage!, intensity: self.filterIntensity!, isPremium: false)
                }
                
            }
        }
    }
    
    func isPlaying() -> Bool {
        return !metalView!.isPaused
    }
    
    func play() {
        if isVideoBackground{
            
            UIView.animate(withDuration: 0.2, animations: {
                self.backgroundImageView?.isHidden = true
            }) { (isComplete) in
                self.metalView?.isPaused = false
                self.videoSource?.start()
            }
            
//            self.videoSource?.start(progress: { (time) in
//                print(time)
//            }, completion: { (isComplete) in
//
//            })
            print("background play")
            
        }
        
    }
    func stop()  {
        if isVideoBackground{
            self.videoSource?.cancel()
        }
        
    }
}
`

**Comment by Silence-GitHub** [comment]
There are some problems.

1. We should not enable set needs display for metal view. Remove this
```
metalView?.enableSetNeedsDisplay = true
```

2. Video writer should not be consumer for two sources. Remove one of lines
```
videoSource?.add(consumer: videoWriter!)
lutFilter?.add(consumer: videoWriter!)
```

3. Some filters use insensitive parameters so the effects are hard to recognize. For example
```
BBMetalBoxBlurFilter(kernelWidth: 5, kernelHeight: 5) // hard to see blur effect
BBMetalBoxBlurFilter(kernelWidth: 25, kernelHeight: 65) // easier to see blur effect
```

By the way, I have a question: how to see metal view since `backgroundImageView` covers metal view?

**Comment by R3l0ad3d** [comment]
`metalView?.enableSetNeedsDisplay = true`
i add that when my code is not working . 
and BoxBlur effect more or less that not fact in this time . metal view not show any thing when i change effects , but video play. main problem is metal view not show video after change effect .
another thing you want to know about backgroundImageView that i use for instant effect show to the user , i hide it when video is playing . here i gave you a portion of my code for easily  understand  . 
this code not working on my view . but this code work , i check it to create another project and paste this view . but i cant think so why its not working . thanks for your help .

**Comment by R3l0ad3d** [comment]
i face another problem will you help me again ? Please help me .
when i change metal view frame then video ratio change also . i want to fill video with aspect ratio of metal view frame . i use 
`metalView?.bb_textureContentMode = .aspectRatioFill`

But its work first time when i change frame then video ratio not change to .aspectRatioFill . how can i solve this problem ?

**Comment by Silence-GitHub** [comment]
Sorry, I can not reproduce the problem. Could you please show the code and screenshots (before and after changing fame) ?

**Comment by R3l0ad3d** [comment]
This is main frame that i want to resize
[https://ibb.co/mSgDb94](url)
after change frame 
[https://ibb.co/s3mVCFS](url)
[https://ibb.co/QDxffmd](url)
i just change the frame . and call layoutIfNeeded() . 
and backgroundView code i post here . i just want to change the ratio of this frame .

**Comment by Silence-GitHub** [comment]
Do you use Auto Layout? When Auto Layout updates metal view frame, the internal texture frame dose not change. So the ratio is wrong. For now, update the metal view frame again even using Auto Layout

```
// After updating layout constrains
metalView.frame = newFrame
```
