### ISSUE TITLE
ChromaKey filter on still image does not really work

### ISSUE THREAD

**Issue by aminiz** [Silence-GitHub/BBMetalImage#36]
The following code returns a faded image, not one that has its green removed. 

`BBMetalChromaKeyFilter(thresholdSensitivity: 0.4, smoothing: 1.0, colorToReplace: .green).filteredImage(with: image) `

**Comment by Silence-GitHub** [comment]
Version 1.1.1 fixes it.

**Comment by aminiz** [comment]
Thanks for the prompt response! Your change fixes the bug but I am seeing some quality difference between GPUImage2 and BBMetalImage. 

I had a green-screen background and put the airpod case, key, and finger on top of it. Then I chromakeyed that image with both GPUImage2 (first image) and BBMetalImage (second image). The MacBook is just part of a different image. 

I did not spend time fixing the orientation for the BBMetalImage so please ignore the orientation and aspect ratio issue.

![Screen Shot 2020-05-12 at 8 23 40 AM](https://user-images.githubusercontent.com/4204621/81713796-2b595200-942b-11ea-9b67-bf82727670de.png)
![Screen Shot 2020-05-12 at 8 25 46 AM](https://user-images.githubusercontent.com/4204621/81713802-2d231580-942b-11ea-8cf7-07341c26404f.png)

**Comment by Silence-GitHub** [comment]
Hi, I have a few questions for the bug.

# Q1

Do you use this code ?

```
BBMetalChromaKeyFilter(thresholdSensitivity: 0.4, smoothing: 1.0, colorToReplace: .green)
```

`smoothing` is too high. Try to use default parameters.

```
BBMetalChromaKeyFilter()
```

# Q2

How do you blend two images (Macbook image and chroma key image) ?

# Q3

If the bug is not fixed, could you please show me the original image (green-screen background image)? I will use it to test.

**Comment by aminiz** [comment]
Q1: I get the same result with both.

Q2: I don't actually blend the images. I have an ImageView that shows the MacBook image. On top of that, I have another ImageView that shows the chromakey image. 

Q3: Green screen image is attached. 
![Screen Shot 2020-05-12 at 11 00 47 AM](https://user-images.githubusercontent.com/4204621/81728765-cfe58f00-943f-11ea-85bc-a96f2f098830.png)

**Comment by Silence-GitHub** [comment]
I test the green-screen background image in the demo project with iPhone 7 (iOS 13.3). Here are the results.

The original image.

![IMG_1050](https://user-images.githubusercontent.com/12474830/81730853-08d33300-9443-11ea-8e73-951e7d382fb6.PNG)

The chroma key image. I use the code `BBMetalChromaKeyFilter()`

![IMG_1051](https://user-images.githubusercontent.com/12474830/81730983-2b654c00-9443-11ea-9d54-1d10913af715.PNG)

The chroma key image with sunflower image at the bottom.

![IMG_1052](https://user-images.githubusercontent.com/12474830/81731039-40da7600-9443-11ea-82b3-28bdba8b79fe.PNG)

Are the expected results?

**Comment by aminiz** [comment]
Yes! I was able to get this result as well now. I had made a coding error where I was setting smoothness. Thanks for the help!
