### ISSUE TITLE
Camera output is laggy

### ISSUE THREAD

**Issue by shiwanithakur** [Silence-GitHub/BBMetalImage#38]
Hey,
I am using BBMetalVideoWriter to record video. I should use default AVAssetWriter but I have to blend images with live video capturing so I am using BBMetalVideoWriter. When i start recording, camera start to lag. I would really appreciate your suggestions.

**Comment by Silence-GitHub** [comment]
See issue #29 and this [answer](https://github.com/Silence-GitHub/BBMetalImage/issues/29#issuecomment-582265981).
