### ISSUE TITLE
No rule to process file

### ISSUE THREAD

**Issue by iDevid** [Silence-GitHub/BBMetalImage#4]
Hi all, when compiling for iOS Simulator Xcode give the following warning, do you know how to fix this?
Of course I don't use Metal on iOS Simulator, but this is annoying :(

:-1: no rule to process file '/dir/Pods/BBMetalImage/BBMetalImage/BBMetalImage/BBMetalColorDodgeBlendFilter.metal' of type 'sourcecode.metal' for architecture 'x86_64' (in target 'BBMetalImage')

**Comment by Silence-GitHub** [comment]
Xcode 11 fixes it.
