### ISSUE TITLE
SwiftUI tip

### ISSUE THREAD

**Issue by ozgurshn** [Silence-GitHub/BBMetalImage#40]
It's super easy to test the filters live on SwiftUI. Check this out.

```
import SwiftUI
import BBMetalImage

struct SwiftUIView: View {
    var body: some View {
        let image = UIImage(named: "sunflower")!
        return VStack {
            
            Image(uiImage: image).resizable().scaledToFit()
            
            Image(uiImage:BBMetalBrightnessFilter(brightness: 0.15).filteredImage(with: image)!).resizable().scaledToFit()
        }
    }
}
``` 
<img
width="1111" alt="Screen Shot 2020-05-21 at 11 51 02" src="https://user-images.githubusercontent.com/2404074/82541633-737a2200-9b59-11ea-878f-d52ccf3bafb8.png">

**Comment by ozgurshn** [comment]
I added filter picker and eperiment right while developing. https://twitter.com/ozgr_shn/status/1263400148702543872?s=20

**Comment by ozgurshn** [comment]
I forked and added my experiments there as SwiftUI supported only iOS 13+ https://github.com/ozgurshn/BBMetalImage

**Comment by Silence-GitHub** [comment]
Cool! Anything I can help?

**Comment by ozgurshn** [comment]
Thanks. I wonder how can I add swiftUI samples to this repo. They are supported on İOS 13+.

**Comment by Silence-GitHub** [comment]
I don't think it is necessary. Processing image and displaying processed image are independent. The samples should focus on processing image or video.

**Comment by ozgurshn** [comment]
Okey then I close this issue.
