### ISSUE TITLE
Release mood filter now working .

### ISSUE THREAD

**Issue by R3l0ad3d** [Silence-GitHub/BBMetalImage#41]
I use this library in my app for filter . debug mood its work fine . today i upload my app for test in testflight but no filter show and white image produce . then i try to build release mood in my device then the result same no image return from my filter function . i use this library one of my app thats live on app store and works fine . same code i run in release mood today its not working . it is version problem ? or something else . please help me .

**Comment by Silence-GitHub** [comment]
Any difference for your code in debug and release mode? Do you use anything like `#if`?

**Comment by R3l0ad3d** [comment]
No . for confirmation i make a test project and run a filter in release mode thats not work . please check . my mac version 10.15.5 beta , xcode version 11.5 . please check this

**Comment by Silence-GitHub** [comment]
I get an empty image on Xcode 11.5 release mode. It works well in Debug mode. I change the code for creating `CGImage` from `MTLTexture` and it works well in both modes. Please update the code to version 1.1.2

**Comment by R3l0ad3d** [comment]
thanks
