### ISSUE TITLE
BBMetalView to render image

### ISSUE THREAD

**Issue by knightbenax** [Silence-GitHub/BBMetalImage#44]
Is it possible to use BBMetalView to render images from the image processing pipeline? The docs say nothing about that.

**Comment by Silence-GitHub** [comment]
BBMetalView can receive and display image texture, but can not output texture. If you need to process texture displayed on the metal view, you can set up filter chain like this

```
let imageSource = ...
let filter1 = ...
let metalView = ...
let filter2 = ...
imageSource.add(consumer: filter1)
    .add(consumer: metalView)
filter1.add(consumer: filter2)
    .add(consumer: ...)
```
