### ISSUE TITLE
Blend camera capture with timeframe image frame by frame, like timestamp

### ISSUE THREAD

**Issue by BootMaker** [Silence-GitHub/BBMetalImage#46]
I used GPUImage earlier to blend camera capture with UNIX time stamps for recording experiments and syncing video with measurement data. 
I’d like to blend images with camera stream and it works well, but I’d like to change the image on every frame, as the time stamps change. Which point could I catch the video frames asynchronously and blend it with images frame by frame and save it as one video file? Is the time information of the video (sample time) is available and accurate for using as timestamp?

**Comment by Silence-GitHub** [comment]
@BootMaker Hello, thanks for issuing. I add `BBMetalMultipleImageSource` to output multiple-image textures. You can use it to blend multiple images. Please see the example code in `MultipleImageBlendVC.swift` file of demo project. The code is in master branch, but has not been added to CocoaPods. Please check if it can help you.

**Comment by BootMaker** [comment]
**@Silence-GitHub** Thanks for the fast answer and taking the problem seriously. Appreciate it.
Super support!

At first blink it's a really good solution, I will try it and feed you back soon.
It was funny that you tried the same counter trick (if self.frameCount == 30...) than me in the earlier version of my application, saving resources :)

**Comment by BootMaker** [comment]
I tried hard to embed your version to my app, but after several days of effort I have to say that even it's a useful improvement, I think maybe you misunderstood the problem and the question.
My problem is that I'd like to change the image on every camera frame. So I have to blend a new image with the current timestamp `NSDate().timeIntervalSince1970` with the camera frame texture, so somewhere around the `camera.willTransmitTexture` I suppose.
As the frame/texture has a correct time, I suppose it's the exact time when the camera recorded that frame, the best and most exact would be to get this time and take it on an UIImage and blend this with the camera frame.

**Comment by Silence-GitHub** [comment]
@BootMaker Maybe I misunderstood. Now I have a few questions.

1. About what you need to do. Suppose you have an image `Image_A`. You need each timestamp of camera frame, and draw the timestamp on `Image_A`. After drawing, you get `Image_B`. Finally, you need to blend `Image_B` with camera frame texture. Is it correct?

2. About timestamp. You can get timestamp using `NSDate().timeIntervalSince1970` in `camera.willTransmitTexture` closure. But it is not the accurate timestamp. The accurate timestamp of camera frame is presentation timestamp of `CMSampleBuffer` (use `CMSampleBufferGetPresentationTimeStamp` function). The timestamp type is `CMTime`. I can provide the timestamp as closure parameter in `camera.willTransmitTexture` closure. Do you need it?

**Comment by BootMaker** [comment]
Thanks for the fast answer!

1. Yes, that's correct!
Actually I'd like to stamp 2 strings (text info) on the frames, one is the timestamp as you wrote correctly and another text with some ID about the measurement but it's the same for every frame. Which is important the image A actually a clear, alpha zero image just to carry the timestamp.
(Actually it's quite useful feature as timestamping is a general need in academic or industrial researches.)

2. Yes you are correct, the accurate timestamp of camera frame is really the presentation timestamp of `CMSampleBuffer`, and it would be fine to get it in` camera.willTransmitTexture` closure.

But the question is where can I blend the images with the video? I suppose somewhere in ` camera.willTransmitTexture`?, am I right? I tried but couldn't' solve it..., thanks for your guiding...

**Comment by Silence-GitHub** [comment]
@BootMaker Please try version 1.1.3

Here is sample code.

```
camera = ...
metalView = ...
videoWriter = ...
imageSource = BBMetalStaticImageSource(image: image)
let filter = BBMetalNormalBlendFilter()
camera.add(consumer: filter)
    .add(consumer: metalView)
imageSource.add(consumer: filter)
    .add(consumer: videoWriter)
camera.willTransmitTexture = { [weak self] texture, sampleTime in
    guard let self = self else { return }
    
    UIGraphicsBeginImageContext(image.size)
    image.draw(at: .zero)
    NSString(string: "\(sampleTime.seconds)")
        .draw(at: CGPoint(x: 0, y: image.size.height * 0.5))
    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    
    if let image = image {
        self.imageSource.update(image)
    }
    self.imageSource.transmitTexture()
}
```

**Comment by BootMaker** [comment]
@Silence-GitHub It's working!
Thanks for the fast and effective support.
Clean code, nice library, good demos, thanks for your work.
