### ISSUE TITLE
outputTexture is nil on some images within the Assets

### ISSUE THREAD

**Issue by iDevid** [Silence-GitHub/BBMetalImage#5]
I tried to create a filteredImage from an image, but it returns nil.
The strange thing is that this image is under the Assets folder, If I move it in the general projects file, the filter then works.

Have you any idea?

**Comment by iDevid** [comment]
You could test it out with this image:
![test](https://user-images.githubusercontent.com/1254022/60926967-7b660600-a2a8-11e9-8de5-1ce78fcde15e.png)

**Comment by Silence-GitHub** [comment]
Thanks for issuing me. I found the problem.

To process an image, we need the metal texture of the image. We use `MTKTextureLoader` and `CGImage` to get the metal texture. When the test image is a general project file, the color space of CGImage is RGB. However, when the test image is under the Asset folder, the color space becomes Monochrome. MTKTextureLoader can not decode image for Monochrome color space. So we can not get the metal texture of the image. The similar problem can be found [here](http://www.openradar.me/31722523).

To solve the problem:
1. Create an empty metal texture
2. Create `CGContext` with device RGB color space, draw the CGImage, and get the bitmap data
3. Copy bitmap data to the metal texture

I will fix it in the next version.

**Comment by Silence-GitHub** [comment]
Version 1.0.1 fixes it.

**Comment by iDevid** [comment]
Image Quality seems very bad, the same Filter trough CIFilter is very much better.
You can see in the demo, that if you apply the filter on this type of images, they become shelled.

**Comment by Silence-GitHub** [comment]
I have not reproduced the bad quality problem. Could you please show me the code? It will help me if there is a simple demo.

**Comment by iDevid** [comment]
I just replaced the sunflower image in the demo with a monochrome Image
![ezgif-2-b7cee2b2ca84](https://user-images.githubusercontent.com/1254022/61111925-01da3d80-a48b-11e9-81a8-3b1526658d30.gif)

**Comment by Silence-GitHub** [comment]
I test `BBMetalColorMatrixFilter` and `CIFilter` with `CIColorMatrix`. It is true that they are different, and monochrome image becomes shelled after apply `BBMetalColorMatrixFilter`. But I can not tell which filter gets good or bad image quality. I also test `GPUImageColorMatrixFilter` (famous GPUImage framework). It has the same result as `BBMetalColorMatrixFilter`, making monochrome image shelled. Maybe `CIColorMatrix` uses different shader, or contains more image processing steps.
