### ISSUE TITLE
Audio out of sync after switching camera while recording

### ISSUE THREAD

**Issue by blurtime** [Silence-GitHub/BBMetalImage#52]
First of all, I love this pod and like all the features it has. Thank you for making it open source!
However, I encountered one small problem today. If I record a video and switch the camera while doing so, the resulting video's audio will:
1. be interrupted shortly at the time of the switch and the more often the camera is switched, the more audio and video are not in sync.
2. be missing entirely at the end of the video (switching the camera very often to makes it very evident).

My explanation: Point 2 appears to follow from point 1 but that's how I noticed this issue in the first place. The audio seems to just go missing during some fraction of the switch and the audio after that is not added in sync to the video but rather to the frames where some audio went missing (basically "filling in the audio blanks"). Therefore, at the end of the video, there's no audio. 

I tried looking into the code for three hours now (it's 2:30 AM here in Central Europe now) but I only know the basics of AVFoundation and, unfortunately, couldn't find anything suspicious - probably because I have a hard time understanding some parts of the code.

I know your time is very valuable but I would appreciate it if you could check out this problem. It would essentially be a - much appreciated - cherry on top of this wonderful pod if one could fix this issue. Looking forward to your feedback. Good night! ✌️

**Comment by Silence-GitHub** [comment]
@blurtime Hi

Audio and video out of sync has been discussed [here](https://stackoverflow.com/questions/40494841/seamless-audio-recording-while-flipping-camera-using-avcapturesession-avasset/56572852#56572852). Version 1.1.4 adds adjusting video and audio sample time feature. However, there is still a little bit audio out of sync after switching camera while recording. Please try version 1.1.4 to see if it is acceptable.

Here is sample code.

```
videoWriter.start (startHandler: { [weak self] time in
    guard let self = self else { return } // We must use weak self to prevent retain cycle, because camera retains video writer.
    self.camera.adjustSampleTime(time)
})
```

The code about adjusting sample time can be found in `captureOutput(_:didOutput:from:)` function of `BBMetalCamera` class. If you know how to adjust sample time to make video and audio sync accurately, please share the idea or create a pull request.

**Comment by blurtime** [comment]
Hi @Silence-GitHub,
Thank you for taking the time to address my issue. I just checked out version 1.1.4 and, unfortunately, I fear the issue was aggravated. In the new version, the switching process seems to do to the following in the resulting video file from what I can see:

- The video from the old camera is playing with audio in sync.
- I tap the button to switch the camera and as soon as I have hit that button, immediately in the resulting file, the audio from *after* the switch starts playing although there is still video playing from *before* the switch. I'll call the point where the audio from after the witch starts playing "Point 1". (It's easiest to hear this interruption when recording a music video where the singers lip-sync their music.)
- After "Point 1" the video from before the switch is still playing. It seems to keep going for the same amount of time it takes the camera to switch - until it reaches "Point 2". The frames during the switch (just a black screen in the file) appear to be cut out almost entirely in the new version.
- Now, after "Point 2" the video seems to be lagging behind, though (the audio is played before the video). 

My thoughts on what is happening now:

One thing seems to have prevailed in both versions of the pod: Some audio is suddenly skipped for a moment and, therefore, lost. It is only an estimate based on my perception but I would say that the amount of audio lost is about the same as in the previous version. Let's call this lost audio time *t(A)*. *t(A)* is the reason there is an "interruption" (at least it sounds like that when recording e.g. a music video) at Point 1. 
In the new version, the video doesn't seem to account for the lost audio which would require it to drop a few frames such that the video is also skipping *t(A)* at some point during the switch. In the end, we are left with video that is out of sync (lagging behind) and audio that is *n * t(A)* shorter than it should be - leading to no audio at the end (*n* denoting the number of switches during one video).

An idea on how to fix it with questions:

1. I am going to look into the code this Sunday or even earlier if I have time on my hands. But I think a good place to start would be to first address the issue of audio being dropped during the switch. It would be best if the audio could just keep playing without being interrupted (or more accurately, without some audio suddenly being skipped) such that the only thing one has to worry about is how the video relates to the audio in terms of synchronization. This is how social media giants do it as far as I can tell, too. Do you have an idea on how we could address this in the first place?
2. Then drop or feed-in (depending on what is needed) a few frames such that they are in sync during the switch.

Finally, I have a question regarding the SO question. I actually found this question two days ago when I was first looking into this problem and actually voted up the question as well as the swift answer. In the answer, we are told that the frame rate needs to be consistent and I was wondering if the frame rate is consistent? I found the function [`setFrameRate`](https://github.com/Silence-GitHub/BBMetalImage/blob/8b371d7ebad09f0e743e27f776ff0107a0ae64ca/BBMetalImage/BBMetalImage/BBMetalCamera.swift#L449) but I couldn't find it being called anywhere so I would assume it is up to me to determine the frame rate. Or am I overlooking something?

I am looking forward to hearing from you! I appreciate you taking the time!

**Comment by blurtime** [comment]
Hi @Silence-GitHub,

First of all, screw me, I am dumb. The issue is pretty much fixed after calling the function you provided in the `videoWriter.start`. Apparently, I had an `if` (due to something else I've been working on) that prevented it from being called. Now that I called it the problem is essentially fixed. I am VERY grateful for your help!

But I do have a few questions and also a suggestion for improvement:

- Firstly, you've created a `starterHandler`. How should it be used and what are its advantages? The same goes for BBMetalVideoWriterProgressType. I used to use `start` like so:

      // This is not what it will look like when I'm done with the my camera class, it's rather provisional atm
      videoWriter.start { [weak self] (type) in
        switch type {
        case let .video(time, success):
            if !success { print("video recording not successful") }
            
            guard let self = self, let cmSeconds = self.cmTimeToSeconds(time) else {
                print("Video time = \(time), success = \(success)")
                return
            }
            self.camera?.adjustSampleTime(time) // actually calling it now :D
            if let timeInterval = self.timeInterval {
                let elapsedTime = cmSeconds - timeInterval
                DispatchQueue.main.async {
                    self.animateClipProgress(with: elapsedTime)
                    self.filterButton.titleLabel?.text = "\(elapsedTime.round(to: 2))"
                }
            } else {
                self.timeInterval = cmSeconds
            }
            
        case let .audio(_, success):
            if !success { print("audio recording not successful") }
            
        }
      }
- Secondly, when should I call the function stopping to adjust the time (`stopAdjustingSampleTime`)? 
- Suggestion: The audio and video are now in sync in the resulting video file. However, now both - video and audio - are skipped in sync. I would prefer, though, if audio was not skipped and one could hear the audio during the switch - with audio and video still in sync after that. Do you think this would possible?

Thank you for solving this problem pretty much! Much appreciated!

**Comment by Silence-GitHub** [comment]
@blurtime Hi, thanks for your idea. In version 1.1.5, camera uses two independent `AVCaptureSession` for video and audio respectively. When switching camera position, video session is interrupted, but audio session keeps working. We do NOT adjust video or audio sample time. The resulting video file syncs well.

To enable independent audio session, set `multitpleSessions` true when creating camera.

```
camera = BBMetalCamera(multitpleSessions: true)
```

Please try version 1.1.5, just one line of code.

Note: do NOT allow the user to switch camera position too frequently (tap switch button multiple times per second). Both version 1.1.4 and 1.1.5 will out of sync if switching too frequently.

**Comment by blurtime** [comment]
IT WORKS LIKE A CHARM!! Thank you for fixing this issue so swiftly and taking the time - appreciate it lots! You are the best! 😁
I'll make sure users won't be able to switch too frequently, thank you for the note
