### ISSUE TITLE
Application of Filter rotates image

### ISSUE THREAD

**Issue by mnfro** [Silence-GitHub/BBMetalImage#53]
Hi @Silence-GitHub, I'm having an issue with static application of filters. 
I init the `imageSource` in `viewDidLoad` with the unfiltered image (obtained from the Photo Library):
```swift
    override func viewDidLoad() {
        super.viewDidLoad()

        imageView.contentMode = .scaleAspectFit
        imageView.clipsToBounds = true
        imageView.image = image
        
        imageSource = BBMetalStaticImageSource(image: image)
    }
```
Then, when I apply a lookup filter to the image, the image rotates by 90° counter-clockwise. This does not happen for all images. 
```swift
        imageSource?.removeAllConsumers()
        let filter = filterAtIndex(currentFilterIndex)
        imageSource?.add(consumer: filter!)
                    .runSynchronously = true
        imageSource?.transmitTexture()
        metalContainerView.image = filter?.outputTexture?.bb_image
```
Have you ever notice that?

**Comment by Silence-GitHub** [comment]
Redrawing image may help. See https://stackoverflow.com/questions/42098390/swift-png-image-being-saved-with-incorrect-orientation

Could you please upload the original image? I will test the image.

**Comment by mnfro** [comment]
Here is the [image](https://user-images.githubusercontent.com/63849808/90103767-56618380-dd43-11ea-8c49-fffa96d184cd.JPG)
I'll take a look at the link you sent.

**Comment by Silence-GitHub** [comment]
Version 1.1.6 fixes it. Please try version 1.1.6

**Comment by mnfro** [comment]
Thank you!
