### ISSUE TITLE
Black output on iPad

### ISSUE THREAD

**Issue by skliarovartem** [Silence-GitHub/BBMetalImage#56]
I have iPad 6th gen, and when trying to apply filter to big picture it shows just black image as result, but CIFilters works properly, and my custom shaders filters work also good. 
I don't have this problem on iPhone

**Comment by Silence-GitHub** [comment]
Please try version `1.1.6`. If it dose not work, please upload the original image. I will test the image.

A few questions:

1. Which filter not work on iPad 6? All filters?

2. Your custom shaders filters work. Do you mean custom `CIFilter` or `BBMetalBaseFilter`?
