### ISSUE TITLE
Can you create a vignette effect? 

### ISSUE THREAD

**Issue by JamesJunsungKim** [Silence-GitHub/BBMetalImage#57]
I was looking for a way to create a vignette effect but I've been having bad luck so far.

I see that GPUImage has it and even GPUImage3 has it yet I have no idea how to convert it to a way BBMetalImage works.

Can you please consider adding it to the list of the built-in filters?

Thank you very much.

**Comment by Silence-GitHub** [comment]
Please try version 1.1.6 and use `BBMetalVignetteFilter`

**Comment by JamesJunsungKim** [comment]
checked that it works well.

Thank you:)
