### ISSUE TITLE
iOS 10 Crash

### ISSUE THREAD

**Issue by iDevid** [Silence-GitHub/BBMetalImage#6]
Hello, I issued a crash on iOS 10 for color matrix filter

This is the stack trace:
`
0  BBMetalImage                   0x11959f6 globalinit_33_E52B5AAF7857E3D0EE385C3EE3E5AC06_func6 + 111
1  libdispatch.dylib              0x1d3fac65 dispatch_once_f + 42
2  libswiftCore.dylib             0x2bc31ef swift_once + 22
3  BBMetalImage                   0x118ce89 $s12BBMetalImage0A10BaseFilterC18kernelFunctionName12useMPSKernelACSS_SbtcfcTf4gnn_n + 210
4  BBMetalImage                   0x1194f4f $s12BBMetalImage0A17ColorMatrixFilterC05colorD09intensityAcA0A9Matrix4x4V_Sftcfc + 140
`

**Comment by iDevid** [comment]
Ok i tested it on an iPhone 5, seems that MTLCreateSystemDefaultDevice() is nil

**Comment by Silence-GitHub** [comment]
Metal requires A7 devices or higher. See https://stackoverflow.com/questions/24183405/metal-failed-creating-a-default-system-device-on-iphone5-ios8
