### ISSUE TITLE
Multiple video sources

### ISSUE THREAD

**Issue by damikdk** [Silence-GitHub/BBMetalImage#7]
Hi! Thanks for amazing framework.

I have a few videos with alpha channel and I need to blend them into one. In background if possible.

I'm trying to implement [GPUImage2](https://github.com/BradLarson/GPUImage2) now, but it's too raw. I was able to export 18 seconds long videos in 5 seconds (without presenting it, just processing in background) with GPUImage2, but I got frame drops and pixelbuffer bugs.

Can I achieve success with BBMetalImage?

**Comment by damikdk** [comment]
Well, I got something after a couple of hours. Here is my changes from your cool demo project:

```
let url = Bundle.main.url(forResource: "test_video", withExtension: "mov")!

// First VideoSource
videoSource = BBMetalVideoSource(url: url)

// Second VideoSource (the same video file)
videoSource2 = BBMetalVideoSource(url: url)

// RotateFilter will be apply on videoSource2 just for making the difference between videos
filterRotate = BBMetalRotateFilter(angle: 45, fitSize: true)
filterBlend = BBMetalSourceOverBlendFilter()

videoSource
    .add(consumer: filterBlend)
    .add(consumer: metalView)

videoSource2
    .add(consumer: filterRotate)
    .add(consumer: filterBlend)

filterBlend.add(consumer: videoWriter)
```

It's renders almost perfect, but when I trying to record it, I getting AVAssetWriter with status after 2-4 seconds. The same problem with GPUImage2 :(

``Asset writer or video input is not ready for writing this frame``

**Comment by damikdk** [comment]
And I got memory leak and crash when I tried to disable ``playWithVideoRate``

**Comment by Silence-GitHub** [comment]
Thanks for issuing me.

To blend two videos or more, we should make sure that the videos transmit video frame textures at the same speed (e.g. video A transmits frame 1, video B transmits frame 1, video A transmits frame 2,  video B transmits frame 2...). `BBMetalVideoSource` dose not guarantee the same speed now. So the blended texture will be wrong.

I will try to add blending videos feature in the new version.

**Comment by Silence-GitHub** [comment]
I write a sample demo at branch `multiple_video`. `MultipleVideoBlendVC` is the demo view controller, blending two videos. `MultipleVideoSource` is used to transmit video frame textures at the same speed. Hope it will help you.

**Comment by damikdk** [comment]
Wow, thanks, dude! 

Yesterday I already wrote simple AVFoundation blender for our task, but maybe we will use your awesome lib too. Again, thank you for quick responses.

**Comment by fanguohuiruan** [comment]
hi, BBMetalBaseFilter or implements ， i call it  BBMetalBaseFilter's.  i just qustion you that BBMetalBaseFilter's can record a view's animation to a BBMetalVideoWriter. and insert this to video to a limited duration into other much longer video.

**Comment by fanguohuiruan** [comment]
i want to record the animation of a view's all moves. what can i use with the BBMetalImage. Thank you very much!

**Comment by Silence-GitHub** [comment]
@fanguohuiruan I open a new issue [How to record a view animation](https://github.com/Silence-GitHub/BBMetalImage/issues/25)

**Comment by blurtime** [comment]
@damikdk Do you still have the code? `MultipleVideoBlendVC` works great if the video is already recorded. But I am currently looking into applying a video as a filter (e.g. with an alpha value of 0.5). I would greatly appreciate it if you could share your code.

**Comment by damikdk** [comment]
@blurtime actually, I have some, but I am not sure about NDA. Our code are blending videos from files (not views) with default AVAssetExportSession. It’s not that hard and you can check [similar code](https://github.com/rubygarage/media-watermark/blob/master/Sources/Classes/Core/MediaVideoProcessor.swift) in [rubygarage/media-watermark](https://github.com/rubygarage/media-watermark). But it works only with images, text and GIFs.

**Comment by blurtime** [comment]
@damikdk Ok, I was looking for real-time applications. Blending existing files shouldn't be a problem - even as a filter, since @Silence-GitHub has already provided some awesome code for this. But this filter currently still requires an existing file. I suggested in #69 that he could one by one add filters whenever he has time. I already greatly appreciate his code and that he's decided to make BBMetalImage open source.
Don't want to create problems for you. Thank you, though, for the tips!

**Comment by schumy** [comment]
I'm using this now because I had the same need and I end up forking it, since this branch hasn't been updated(multiple_video) for a while.
Is there any plan to actually release this?

**Comment by Silence-GitHub** [comment]
@schumy `MultipleVideoBlendVC` consumes too much memory. I have not found a solution for the problem, so can not release it. Sorry.
