### ISSUE TITLE
Can BBMetalImage be used with AVComposition?

### ISSUE THREAD

**Issue by MQZHot** [Silence-GitHub/BBMetalImage#72]

**Comment by Silence-GitHub** [comment]
Could you please tell me what you would like to do with AVComposition?

**Comment by MQZHot** [comment]
Use animation to generate videos, such as Lottie.
The video speed generated by AVComposition is wrong, you can take a look  [here](https://github.com/airbnb/lottie-ios/issues/1001).
I want to compose video by frame, just like RecordUIVC in Demo.
