### ISSUE TITLE
Blending live camera video with a video file

### ISSUE THREAD

**Issue by devAlikhani** [Silence-GitHub/BBMetalImage#73]
Hi , thanks for this amazing lib
I'm trying to blend video from a file (mp4) with live camera video, and then record the results 
i couldn't find any example of this approach in Demo code , is it possible to do this?

**Comment by Silence-GitHub** [comment]
@devAlikhani Hi. I've added `CameraVideoBlendVC.swift` to demo project. It's a simple example to blend video with live camera. Maybe you need a custom video source to pause and resume the video output.

**Comment by devAlikhani** [comment]
Thanks @Silence-GitHub for your attention and support , I’ve try to improve your example as well.
