### ISSUE TITLE
MPS Kernels with iOS 12

### ISSUE THREAD

**Issue by FaisalAlneela** [Silence-GitHub/BBMetalImage#76]
I'm using BBMetalGaussianBlurFilter in my app. however, it works fine on most devices but with iOS 12 in iPhone 5s I'm getting an **empty** image. 
I found that any MPSKernel is not working even with the example app.
I'm using Xcode 12.2. Any solution or suggestions for this issue? I will be so thankful.

**Comment by Silence-GitHub** [comment]
Please run the code on iPhone 5s to check whether the Metal Performance Shaders framework supports a Metal device. Please give me a feedback since I don't have iPhone 5s to test.

```
import MetalPerformanceShaders

MPSSupportsMTLDevice(BBMetalDevice.sharedDevice)
```

**Comment by FaisalAlneela** [comment]
@Silence-GitHub Thanks for your response and for this great library, yes actually I found that this device doesn't support Metal Performance Shaders.
I will use CIFilters or I will create my own Gaussian Blur Kernal.
If you can add a Gaussian Blur Kernal I will be so thankful.
