### ISSUE TITLE
is there a way to make a camera with 1:1 ratio frame?

### ISSUE THREAD

**Issue by JamesJunsungKim** [Silence-GitHub/BBMetalImage#83]
Hello, thank you a lot for this awesome framework. 
I was curious if there is a way to make a camera with a 1:1 ratio frame?

thank you in advance!

**Comment by Silence-GitHub** [comment]
Please see https://github.com/Silence-GitHub/BBMetalImage/issues/30#issuecomment-594066056

**Comment by JamesJunsungKim** [comment]
It's not just about the frame size but I believe the camera ratio? is different. when the ratio is 16:9 by default, it's more slender and when it's 1:1 ratio in the default ios camera app, it contains more of the side areas.

based on your response, I assume there is no other way but cropping it to square size which means no different camera ratio.

is that correct?

thanks.

**Comment by Silence-GitHub** [comment]
As far as I know, there is no way to set the camera ratio 1:1. So we need to crop.
