### ISSUE TITLE
Integrating via Cocoapods crash

### ISSUE THREAD

**Issue by Maxtws** [Silence-GitHub/BBMetalImage#85]
While integrating BBMetaImage via cocoapods I've faced a crash which occurs on every usage of any filter. Crashing code is located in BBMetalBaseFilter init method: created MTLLibrary object was nil due to it can't locate any kernels in the bundle. And the bundle itself don't even exist due to my pod file setup don't use frameworks (use_frameworks! is opted out)
Please, fulfill the requirements in readme. use_frameworks! is mandatory in pod file in order for library to function properly.

**Comment by Silence-GitHub** [comment]
Thank you for your suggestion. Done.
