### ISSUE TITLE
Double Camera bug

### ISSUE THREAD

**Issue by monession** [Silence-GitHub/BBMetalImage#86]
Hey. I'm trying to use BBMetalImage to implement double camera app (record video from front and back). I noticed that BBMetalCamera and BBMetalVideoWriter doesn't work as expected. if I call `start()` from second (front) camera, then first (wide angle) camera stops and I see just static image. Is it possible to record video from both cameras and merge them into once file?

**Comment by Silence-GitHub** [comment]
@monession Thanks for issuing. Multiple camera is a good feature. It uses `AVCaptureMultiCamSession` and requires iPhone XR, iPhone XS, iPhone XS Max, iPad Pro (3rd generation) or newer devices. However, I don't have these devices to test now. Maybe you can write a custom camera class. I will add this feature when I have a new device.

**Comment by Silence-GitHub** [comment]
@monession Version `1.1.12` adds `BBMetalMultipleCamera` supporting multiple camera. See demo project for detail.
