### ISSUE TITLE
Transform filter 

### ISSUE THREAD

**Issue by alyfreym** [Silence-GitHub/BBMetalImage#88]
how to transform using BBMetalTransformFilter relative center?

**Comment by Silence-GitHub** [comment]
Sorry, I am not sure what "relative center" exactly means. Create `BBMetalTransformFilter`, set `transform` just like setting `transform` for `UIView`. Translation x and y are specified in pixels. Please see the demo project.

**Comment by bharara** [comment]
I think what @alyfreym is asking is, how we can make sure the center remains the same after the transformation. Currently transforming keep the top left at origin

**Comment by bharara** [comment]
@alyfreym did you solved it? If yes, how?

**Comment by Silence-GitHub** [comment]
Please try version `1.1.11`. `BBMetalTransformFilter` adds `anchorPoint`. Set `anchorPoint` (0.5, 0.5).
